### ISSUE TITLE
Activity Combobox Home Page

### ISSUE THREAD

**Issue by Tjebbedebruh** [svsticky/constipated-koala#1137] opened 2024-11-03 21:07 UTC
### Expected behaviour
- Expected to see the activities from the year displayed in the combobox. 
- Expected to see the activities from the year 2024-2025 when pressing the combobox item "2024-2025"
### Actual behavior
- The combobox text always displays 2024-2025 
- When switching to the year 2024-2025 it doesn't change the activities list to the activities of that year and instead displays the same year it was in.

### Steps to reproduce
user
browser: Chrome and Edge 
- open the homepage on koala 
- click on the combobox on the left and switch to a previous year
- now you see that the text doesn't change with the year you switched to
- when switching back to the year 2024-2025 it doesn't refresh the activity list

![image](https://github.com/user-attachments/assets/f6633a25-8c93-4458-bd7a-3767f915c7bb)
_coverd personal information because of privacy_

**Comment by SilasPeters** [comment] 2024-11-05 19:19
Thanks so much for your issue! However, ~~it's a you problem!~~ it's a duplicate of a (quite old) other issue: #833. If someone is done with their current project I will let them look into this.

**Closed by SilasPeters** 2024-11-05 19:19 UTC
